function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t481_setWidth(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t481');Array.prototype.forEach.call(menuBlocks,function(menu){var alignment=menu.getAttribute('data-menu-items-align');var leftContainer=menu.querySelector('.t481__leftcontainer');var rightContainer=menu.querySelector('.t481__rightcontainer');var centerContainer=menu.querySelector('.t481__centercontainer');var mainContainer=menu.querySelector('.t481__maincontainer');var centerContainerList=centerContainer?centerContainer.querySelectorAll('li'):[];var maxWidth=Math.max(t481_getFullWidth(leftContainer),t481_getFullWidth(rightContainer));maxWidth=Math.ceil(maxWidth);var paddingWidth=40;var centerWidth=0;Array.prototype.forEach.call(centerContainerList,function(list){centerWidth+=t481_getFullWidth(list)});var leftSide=menu.querySelector('.t481__leftside');var rightSide=menu.querySelector('.t481__rightside');var mainContainerWidth=t481_getFullWidth(mainContainer);if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(alignment==='center'||!alignment){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px'}}else{if(leftSide)leftSide.style.minWidth='';if(rightSide)rightSide.style.minWidth=''}})}
function t481_getFullWidth(element){if(!element)return 0;var marginLeft=element.style.marginLeft||window.getComputedStyle(element).marginLeft;var marginRight=element.style.marginRight||window.getComputedStyle(element).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return element.offsetWidth+marginLeft+marginRight}
function t509_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t509');if(!container)return;var images=rec.querySelectorAll('.t509__blockimg');t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)});for(var i=0;i<images.length;i++){var image=images[i];var imageWidth=image.getAttribute('data-image-width');var imageHeight=image.getAttribute('data-image-height');if(imageHeight.indexOf('vh')===-1){imageHeight=parseInt(imageHeight,10)}else{imageHeight=parseInt(imageHeight,10)/100*window.innerHeight}
var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;image.style.paddingBottom=imagePadding+'%'}
if(window.innerWidth>960){var desktopImage=rec.querySelector('.t509__desktopimg');if(desktopImage){var height=desktopImage.clientHeight;var textWrappers=rec.querySelectorAll('.t509__textwrapper');for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height=height+'px'}}}}

function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}